CREATE TABLE IF NOT EXISTS influencer_details (
    inf_id serial PRIMARY KEY,
    inf_firstName VARCHAR (256),
    inf_lastName VARCHAR (256),
    inf_gender VARCHAR (256),
    inf_phoneNumber NUMERIC,
    inf_email VARCHAR (256),
    inf_password VARCHAR (256),
    inf_createdAt VARCHAR (256),
    inf_description VARCHAR (10485760),
    inf_address VARCHAR(256),
    inf_city VARCHAR(256),
    inf_state VARCHAR(256),
    inf_gst_country VARCHAR (256),
    inf_pincode VARCHAR (256),
    inf_gst_no VARCHAR (256),
    inf_gst_doc_url VARCHAR (256),
    inf_legalbillingname VARCHAR (256), 
    inf_email_status BOOLEAN,
    inf_mobile_status BOOLEAN,
    inf_OTP NUMERIC,
    inf_country VARCHAR (256),
    inf_offline_status VARCHAR (256) DEFAULT FALSE,
    inf_profile_thumbnail_image VARCHAR (256),
    inf_profile_banner_image VARCHAR (256),
    inf_account_deactivation BOOLEAN,
    inf_profile_details_filled BOOLEAN NOT NULL DEFAULT FALSE,
    inf_reason_for_deactivation VARCHAR (256),
    inf_facebook_link VARCHAR (256),
    inf_linkedin_link VARCHAR (256),
    inf_twitter_link VARCHAR (256),
    inf_instagram_link VARCHAR (256),
    inf_carousel_first_image VARCHAR (256),
    inf_carousel_second_image VARCHAR (256),
    inf_carousel_third_image VARCHAR (256),
    inf_carousel_video_link VARCHAR (256),
    inf_carousel_thumbnail_image_link VARCHAR (256),
    inf_business_type VARCHAR (256),
    inf_level_status VARCHAR (256) NOT NULL DEFAULT 'LEVEL_ZERO',
    inf_profile_verify_status VARCHAR (256),
    inf_profile_reject_reason VARCHAR (256),
    inf_starting_price VARCHAR (256),
    inf_rzp_account_id VARCHAR (256),
    inf_lastseen VARCHAR (256),
    inf_total_sales INT NOT NULL DEFAULT 0
);